### ISSUE TITLE
[ci] increase ES heap size for branch testing

### ISSUE THREAD

**Issue by dmlemeshko** [elastic/kibana-load-testing#102]
At the moment we are running up to 400 concurrent users in branch testing. By increasing it we are hitting ES SQ limit that potentially can be avoided by bumping ES heap size: from 1G to 2/4/6, should be tested.

Blocked by elastic/kibana/issues/99494

**Comment by tylersmalley** [comment]
This can now be done by setting the `ES_JAVA_OPTS` environment variable. 

For example:

`ES_JAVA_OPTS="-Xms5g -Xmx5g" yarn es snapshot`

**Comment by dmlemeshko** [comment]
closed by elastic/kibana/pull/101906
